// DO NOT EDIT THIS FILE MANUALLY.
// This file was created automatically
//   from https://www.iana.org/assignments/cont-disp/cont-disp-2.csv
//     Last-Modified: 2016-06-22 20:57:14 +0000

extension ContentDispositionParameterKey {
  public static let filename = ContentDispositionParameterKey(rawValue:"filename")
  public static let creationDate = ContentDispositionParameterKey(rawValue:"creation-date")
  public static let modificationDate = ContentDispositionParameterKey(rawValue:"modification-date")
  public static let readDate = ContentDispositionParameterKey(rawValue:"read-date")
  public static let size = ContentDispositionParameterKey(rawValue:"size")
  public static let name = ContentDispositionParameterKey(rawValue:"name")
  public static let voice = ContentDispositionParameterKey(rawValue:"voice")
  public static let handling = ContentDispositionParameterKey(rawValue:"handling")
  public static let previewType = ContentDispositionParameterKey(rawValue:"preview-type")
}
