#if !canImport(ObjectiveC)
import XCTest

extension DummyTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DummyTest = [
        ("test_something", test_something),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DummyTest.__allTests__DummyTest),
    ]
}
#endif
